# Generated by Django 4.0 on 2023-04-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_profile_photo_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
