# Generated by Django 4.0 on 2023-04-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_rename_avatar_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiJ5rAqr1pIi6pHOdFGGijRXcE4HLHqWJNSw&usqp=CAU', max_length=200),
        ),
    ]
