# Generated by Django 4.0 on 2023-05-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logbook', '0013_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_Items_user', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_Post_author', to='auth.user'),
        ),
    ]
