# Generated by Django 4.0 on 2023-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0015_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
