# Generated by Django 4.0 on 2023-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0017_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
