# Generated by Django 4.0 on 2023-05-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logbook', '0023_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='profile1',
        ),
    ]
