# Generated by Django 4.0 on 2023-05-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0024_profile12_delete_profile1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile12',
        ),
    ]
