# Generated by Django 4.0 on 2023-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0025_delete_profile12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.AddField(
            model_name='items',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
